### ISSUE TITLE
VoiceOver page refers to Android

### ISSUE THREAD

**Issue by racheleditullio** [appt-org/appt-org#5]
**URL**
[https://appt.org/en/docs/ios/features/voiceover](https://appt.org/en/docs/ios/features/voiceover)

**Suggested improvements**
The following sentence refers to VoiceOver on "Android" instead of "iOS".

The built-in screen reader for Android devices is called VoiceOver.
![android](https://github.com/appt-org/appt-org/assets/39381533/b48bb171-e0d2-4317-8640-3c2c5b0bdba5)

**Comment by JJdeGroot** [comment]
Hi @racheleditullio thanks for reporting this! I missed the notification for this issue. I've just changed it. Content might be cached for a couple hours before it appears updated in your browser.
