### ISSUE TITLE
Currency of articles

### ISSUE THREAD

**Issue by AndrewArch** [appt-org/appt-org#6]
**URL**
[Accessibility articles.](https://appt.org/en/articles)

**Suggested improvements**

- Please provide a date with all articles so we know how recent they are. 
- Also for the [Stats page](https://appt.org/en/stats) - e.g. when was the Netherlands survey undertaken?

**Comment by JJdeGroot** [comment]
Hi @AndrewArch I have just enabled dates for all of our pages in the [article section](https://appt.org/en/articles).

We have decided we will go forward with migrating to Markdown in combination with [Docusaurus](https://docusaurus.io/). In the future, you will also be able to check the commit history of each article on Github. Furthermore, for the accessibility stats, we will daily publish a JSON file in our repo.
