### ISSUE TITLE
iOS Screen rotation

### ISSUE THREAD

**Issue by jamieherrera** [appt-org/appt-org#8]
**URL**
[Please provide the URL of the page where the content is placed.
](https://appt.org/en/stats/screen-orientation-landscape)

**Suggested improvements**
There is a portrait lock on iOS in the Control Center. It is not As helpful as the orientation lock an android, but it does provide the ability to look into portrait mode or if the app is landscape only, you can lock it to one side of the phone. I have used this primarily when lying down, trying to use my phone. Unfortunately, currently, locking into landscape mode  is not a feature, but your page does not specifically state portrait or landscape. 

I suggest that you would include this current portrait lock feature on the page that is referenced, just to acknowledge that you are aware that there is portrait lock, but it's not the same extensive accessibility feature as on android to lock into the most recent orientation.

**Comment by JJdeGroot** [comment]
Hi @jamieherrera thanks for suggesting these improvements. I wasn't aware you could not lock to landscape mode. Will update the content in the near-future.

**Comment by JJdeGroot** [comment]
Hi @jamieherrera sorry for the long delay, this isn't "near-future" anymore. Changes have been made, processing can take a couple hours due to caching. We are in the process of migrating our content to Markdown, which will allow for easier editing.
